First review sprin-1/step-1
ArtemRav/react-burger pull request #1
Opened 2022-10-02 21:05 UTC by ArtemRav

2022-10-02 22:52 UTC, ArslanDev666 commented on src/components/AppHeader/AppHeader.jsx
> +export const AppHeader = props => {
**Надо исправить:** Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

2022-10-02 22:52 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +export const BurgerConstructor = props => {
**Надо исправить:** Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

2022-10-02 22:55 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +BurgerConstructor.propTypes = {
**Надо исправить**

в описании propTypes этого и других компонентов нужно указывать .isRequired у пропсов, без этого не контролируется, что пропс передается

Проверьте во всем проекте

2022-10-02 22:55 UTC, ArslanDev666 commented on src/components/AppHeader/NavItem/NavItem.jsx
> +export const NavItem = props => {
**Надо испарвить**

для этого компонента так же нужно описать PropTypes

2022-10-02 23:27 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Хорошая работа. Приложение начинает обрастать функционалом и уже постепенно проглядывается картина готового продукта.

### **Вы молодцы!**

- Декомпозиция файлов по директориям - практически соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;
- Используются функциональные компоненты;
- Используются css-modules, что тоже очень удобно и является хорошей практикой;

### **Но есть несколько замечаний, которые нужно исправить:**

- background у header не соответствует макету;
- Верстка BurgerIngredients не соответствует макету;
- Верстка BurgerConstructor не соответствует макету, булки не должны скроллится: 

  Ваша верстка: 
   
  ![image](https://user-images.githubusercontent.com/70164458/193480588-855654ce-0e7b-4c1d-8a87-d33ab61ceea4.png)

  Как должно быть:

  ![image](https://user-images.githubusercontent.com/70164458/193480610-f2e994cb-81d3-4c53-9678-ccb0659114f6.png)

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Постарайтесь деструктурировать пропсы, этим вы даёте понять какие пропсы передаются в компонент.

### **Сделает код лучше:**

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

### **_Более подробно эти и более мелкие мелкие замечания, отмечены в коде. Если возникнут какие-либо вопросы, то буду рад на них ответить_**

2022-10-02 23:27 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +            {data.reduce((acc, el) => acc + el.price, 0)}
**Надо исправить:** Цену лучше считать до рендера компонента.

2022-10-02 23:27 UTC, ArslanDev666 commented on src/components/BurgerIngredients/Burgeritem/BurgerItem.jsx
> +export const BurgerItem = props => {
**Надо испарвить**

для этого компонента так же нужно описать PropTypes

2022-10-02 23:27 UTC, ArslanDev666 commented on src/components/BurgerIngredients/BurgerType/BurgerType.jsx
> +export const BurgerType = props => {
**Надо испарвить**

для этого компонента так же нужно описать PropTypes

2022-10-02 23:27 UTC, ArslanDev666 commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +        <Tab value="Булки" active={current === 'Булки'} onClick={setCurrent}>
**Можно лучше:** Обработчик событий лучше вынести в отдельную фунцию. В дальнейшем нужно будет добавить скролл по клику на таб.

2022-10-03 05:37 UTC, ArtemRav commented on src/components/AppHeader/AppHeader.jsx
> +export const AppHeader = props => {
Что в этом месте необходимо исправить? Все импортируемые компоненты используются в AppHeader.

2022-10-03 05:38 UTC, ArtemRav commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +export const BurgerConstructor = props => {
Что в этом месте необходимо исправить? Все импортируемые компоненты используются в BurgerConstructor.

2022-10-03 06:55 UTC, ArtemRav commented on src/components/BurgerIngredients/Burgeritem/BurgerItem.jsx
> +export const BurgerItem = props => {
С PropTypes понятно, а что исправить в импортах?

2022-10-03 08:28 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +export const BurgerConstructor = props => {
В импортах всё в порядке, гитхаб просто так отмечает. Пропсы не использовались вроде. В appHeader тоже самое.

2022-10-03 08:50 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы молодцы!**

- Почти все замечания с 1 ревью, были исправлены.

### **Но есть несколько новых замечаний, которые нужно исправить:**

- В компоненте burgerIngredients, не должно быть скролла у внутренних секций.
  
   ![image](https://user-images.githubusercontent.com/70164458/193537276-85f443b0-be3b-4803-a487-934a31704e98.png)
   

- Неправильно описаны propTypes для ингридиента, там намного больше параметров.

- В некоторых местах в propTypes описаны не все пропсы.

### **_Более подробно эти и более мелкие мелкие замечания, отмечены в коде. Если возникнут какие-либо вопросы, то буду рад на них ответить_**

2022-10-03 08:50 UTC, ArslanDev666 commented on src/components/AppHeader/NavItem/NavItem.jsx
> +      <div style={{ display: 'flex' }} className="icon-wrapper mr-2">
**Надо исправить:** Здесь и далее. Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданные классами. Лучше дать какой-то класс, и там указать уже нужные вам стили.

2022-10-03 08:50 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +          .filter((el, i, arr) => i !== 0 && i !== arr.length - 1)
**Надо исправить:** Фильтрацию лучше делать до рендера, в будущем когда вы изучите useMemo, вы сможете немного оптимизировать это. Также фильтр лучше делать по типу ингредиента, например вот так:
```js
  const bun = constructorIngredients.find(
    (ingredient) => ingredient.type === "bun"
  );
  const ingredients = constructorIngredients.filter(
    (ingredient) => ingredient.type !== "bun"
  );
```

2022-10-03 08:50 UTC, ArslanDev666 commented on src/components/BurgerIngredients/Burgeritem/BurgerItem.jsx
> +}
**Надо исправить:** Описаны не все пропсы которые используются в компоненте.

2022-10-03 08:50 UTC, ArslanDev666 commented on src/components/AppHeader/NavItem/NavItem.jsx
> +}
**Надо исправить:** Описаны не все пропсы которые используются в компоненте.

2022-10-03 08:50 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  )
**Можно лучше**
во многих компонентах дублируется описание PropTypes ингредиента
Лучше вынести его в отдельный файл (можно создать файл prop-types.js в корне src) и переиспользовать описание пропсов ингрединта, а не дублировать

2022-10-03 08:50 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  )
**Надо исправить:** Здесь и во всём проекте. Неправильно описаны propTypes для ингридиента, там намного больше параметров.

2022-10-03 12:23 UTC, ArtemRav commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  )
Переписал логику, подскжите, в таком виде хорошо?

Файл utils/prop-types.js:
import PropTypes from ‘prop-types’
export const burgerListItemPropTypes = () =>
  PropTypes.shape({
    _id: PropTypes.string.isRequired,
    name: PropTypes.string.isRequired,
    type: PropTypes.string.isRequired,
    proteins: PropTypes.number.isRequired,
    fat: PropTypes.number.isRequired,
    carbohydrates: PropTypes.number.isRequired,
    calories: PropTypes.number.isRequired,
    price: PropTypes.number.isRequired,
    image: PropTypes.string.isRequired,
    image_mobile: PropTypes.string.isRequired,
    image_large: PropTypes.string.isRequired,
    __v: PropTypes.number.isRequired
  })
Файл - NavItem.jsx:
NavItem.propTypes = {
  name: PropTypes.string.isRequired,
  color: PropTypes.string,
  link: PropTypes.string
}

2022-10-05 10:14 UTC, merged

2022-10-08 21:37 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  )
Да отлично