Sprint 1/step 2
ArtemRav/react-burger pull request #2
Opened 2022-10-08 14:09 UTC by ArtemRav

2022-10-08 22:06 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы молодцы!**

### **Но есть несколько новых замечаний, которые нужно исправить (Основная часть отмечена в самом коде):**

- Поправить работу с запросами.

- В компоненте `Modal` вынесите магическое значение 27 в именованную константу.

- В директории `components` должен быть компонент App. Компонент `App`, как правило, это основной компонент в React, который выступает в качестве контейнера для всех остальных компонентов;

- Нужно очистить корневую директорию от лишних файлов, которые остались при инициализации create-react-app.

### **_Более подробно эти и более мелкие мелкие замечания, отмечены в коде. Если возникнут какие-либо вопросы, то буду рад на них ответить_**

2022-10-08 22:06 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +                  style={{ cursor: 'pointer' }}
**Надо исправить:** Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданные классами. Лучше дать какой-то класс, и там указать уже нужные вам стили.

2022-10-08 22:06 UTC, ArslanMustafin commented on src/components/AppHeader/AppHeader.jsx
> +  )
**Надо исправить:** В шапке активный пункт меню будет определяться с помощью роутинга, это будет реализовано в 3 спринте, не нужно сейчас это делать через стейт. И тут не нужен useCallback, т.к рендер у нас не зависит от сторонних переменных.

2022-10-08 22:06 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +    return ingredients.filter((_, i, arr) => i !== 0 && i !== arr.length - 1)
**Надо исправить:** лучше сделать такой фильтр, он будет намного надёжнее, потому что мы точно знаем что у нас будет тип bun. И он будет одинаковый. Булку можно вынести в отдельную переменную, мы ведь не знаем, может не будет её, в нулевом индексе массива. 

```js 
  const bun = constructorIngredients.find(
    (ingredient) => ingredient.type === "bun"
  );
  const ingredients = constructorIngredients.filter(
    (ingredient) => ingredient.type !== "bun"
  );
```
И обернуть это в useMemo, не забудьте)

2022-10-08 22:06 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +          {burgersList.map((item, idx, arr) => {
**можно лучше:** Перед отправкой работы, проверьте что все неиспользуемые переменные удалены.

2022-10-08 22:06 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +          <Modal title="" closeModal={() => setModalOpened(false)}>
**Можно лучше:** Лучше вынести, обработчик событий, в отдельную функцию.

2022-10-08 22:06 UTC, ArslanMustafin commented on src/components/BurgerIngredients/Burgeritem/BurgerItem.jsx
> +      onClick={() => openModal(menuItem)}
**Можно лучше:** Лучше вынести, обработчик событий, в отдельную функцию.

2022-10-08 22:06 UTC, ArslanMustafin commented on src/components/BurgerIngredients/BurgerType/BurgerType.jsx
> +          ></BurgerItem>
**Можно лучше:** Можно написать вот так: 
```js
 <BurgerItem
  openModal={openModal}
  menuItem={item}
  key={item._id}
  amount={1}
/>
```
Мы ведь не используем внутри children.

2022-10-08 22:06 UTC, ArslanMustafin commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +  )
**Отлично:** Очень хорошая реализация.

2022-10-08 22:06 UTC, ArslanMustafin commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +              onClick={() => toggleTab(tab)}
**можно лучше:** onClick по умолчанию возвращает, переданный в компонент `value`. Поэтому можно написать просто вот так.
```js
<Tab {...} onClick={toggleTab} />
```

2022-10-08 22:06 UTC, ArslanMustafin commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +            closeModal={() => setModalOpened(false)}
**Можно лучше:** Лучше вынести обработчик событий в отдельную функцию.

2022-10-08 22:06 UTC, ArslanMustafin commented on src/components/IngredientDetails/IngredientDetails.jsx
> +  const { wrapper, title, compound, item, img } = detailsCss
**Можно лучше:** Тут лучше не использовать деструктуризацию, ибо мы теперь можем запутаться с пропсами, и не понять что это переменная отвечает за класс (стили).

2022-10-08 22:06 UTC, ArslanMustafin commented on src/components/Modal/Modal.jsx
> +  )
**Надо исправить**
Вынесите магическое значение 27 в именованную константу `const ECK_KEYCODE = 27`
А также можно занести функцию в useEffect, и тогда нам не нужно будет использовать useCallback, а значит мы освободим немного памяти ^)

2022-10-08 22:06 UTC, ArslanDev666 commented on src/components/ModalOverlay/modal-overlay.module.css
> +  background: #e5e5e5;
**Можно лучше:** Попробуйте использовать тут цвет менее яркий, в идеале, что-то типа такого: `rgba(28, 28, 33, 0.7)`

2022-10-08 22:06 UTC, ArslanDev666 commented on src/components/Modal/modal.module.css
> +  border: 1px solid rgba(76, 76, 255, 0.2);
**Надо исправить:** нужно убрать синюю обводку у блоков, эта обводка на макете нужна только что бы сделать поясняющее описание к этому блоку

2022-10-08 22:06 UTC, ArslanDev666 commented on src/App.jsx
> +    fetchIngredients()
**Надо исправить**
вынесите базовый адрес сервера `https://norma.nomoreparties.space/api` сервера в константу в отдельный файл, а адрес эндпоинта можно оставить в самой функции запроса `${BURGER_API_URL}/ingredients`

**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

**Можно лучше**
хорошо, что обрабатывается ошибка запроса к фзш api, но можно сделать еще лучше - сохранять в state и показывать пользователю ошибку в интерфейсе, чтобы он понимал что происходит

2022-10-09 04:30 UTC, ArtemRav commented on src/components/AppHeader/AppHeader.jsx
> +  )
Возможно что-то не до конца понял, но тут же будет происходить ререндер каждый раз, когда меняется активная вкладка - соответственно после изменения state будет перерисовка, она будет каждый раз приводить к новому определению функции isActiveTab, чтобы этого не происходило, используется useCallback или не верно понимаю процесс жизненного цикла?

2022-10-09 05:00 UTC, ArtemRav commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +              onClick={() => toggleTab(tab)}
Я думал onClick всегда передает только event в обработчик события. Тут value - это props для компонента Tab, у других кастомных компонентов value может и не быть, получается, что onClick по умолчанию возвращает переданный value только в конкретном случае с компонентом Tab, верно понял?

2022-10-09 05:13 UTC, ArtemRav commented on src/components/Modal/Modal.jsx
> +  )
А в чем преимущество useEffect в данной ситуации? Тут ведь useCallback нужен, чтобы избавиться от переобъявления функции каждый раз, когда меняется state. Аналогичную логику можно реализовать и при помощи useEffect(callback, []) - да, но в чем тут соль? И еще по идее может поменяться вызываемая внутри callback функция closeModal, передаваемая в props, т.е. и в useEffect, и в useCallback в зависимостях ее надо будет указать [closeModal] - все идентично, чем useEffect предпочтительнее?)

2022-10-09 05:19 UTC, ArtemRav commented on src/components/Modal/Modal.jsx
> +  )
useEffect — функция, код которой выполняется при монтировании компонента, изменении его пропсов или состояния. В нашем случае нужно, чтобы функция выполнялась при событии onClick, как функцию, размещенную в useEffect можно вызвать на onClick?

2022-10-09 07:56 UTC, ArslanDev666 commented on src/components/AppHeader/AppHeader.jsx
> +  )
Ререндер будет и так, и так происходить, 1 ведь зависимость в компоненте, это `activeTabName`. И при её изменении, будет опять перерисовка.

2022-10-09 08:01 UTC, ArslanDev666 commented on src/components/Modal/Modal.jsx
> +  )
`UseCallback` - тратит достаточно количество памяти на мемоизацию, тут мы можем этого избежать, перенеся, функцию в `useEffect`. В зависимостях достаточно указать `closeModal`. 

```js
  useEffect(() => {
    const onTapEsc = (event) => {
      if (event.keyCode === ECK_KEYCODE) {
        closeModal()
      }
    }
    
    document.addEventListener('keyup', onTapEsc)

    return () => {
      document.removeEventListener('keyup', onTapEsc)
    }
  }, [closeModal])
```

2022-10-09 08:04 UTC, ArslanDev666 commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +              onClick={() => toggleTab(tab)}
В целом зависит от самого компонента, и как мы это сделаем. Это относиться, только к кастомным компонентам, с html-компонентами, все стандартно, там передаётся `Event`

2022-10-09 21:43 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы молодцы!**

### **Есть несколько новых замечаний, которые нужно исправить (Основная часть отмечена в самом коде):**

- Поправить работу скрола в burgerIngredients. При клике на таб, в консоли браузера, вы можете увидеть ошибку.

- Поправить работу с prop-types. В коде выделил моменты.

- В директории `components` должен быть компонент App. Компонент `App`, как правило, это основной компонент в React, который выступает в качестве контейнера для всех остальных компонентов; Вам перенести компонент App в папку components. Это прописано в самом чек-листе.

- Нужно очистить корневую директорию от лишних файлов, которые остались при инициализации create-react-app. А именно setupTests.ts, App.test.tsx.

### **_Более подробно эти и более мелкие мелкие замечания, отмечены в коде. Если возникнут какие-либо вопросы, то буду рад на них ответить_**

2022-10-09 21:43 UTC, ArslanDev666 commented on src/components/Modal/Modal.jsx
> +      const ESC_KEYCODE = 27
**Можно лучеш:** Лучше вынести за пределы компонента.

2022-10-09 21:43 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  }, [ingredients])
**Можно лучше:** Булки не будут меняться, их будет всего 2, и они будут одинаковые. Поэтому лучше написать вот так, и переиспользовать. 
```js
  const bun = useMemo(() => ingredients.find(
    (ingredient) => ingredient.type === "bun"
  ), [ingredients]);
```

2022-10-09 21:43 UTC, ArslanDev666 commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +  }, [])
**Надо исправить:** `tab` - это строка, а именно `tab.name`, которую вы передаете в качестве `value`. И из-за этого перестал работать скролл.

2022-10-09 21:43 UTC, ArslanDev666 commented on src/components/BurgerIngredients/Burgeritem/BurgerItem.jsx
> +export const BurgerItem = ({ menuItem, openModal, amount }) => {
**Надо исправить:** Описаны не все propTypes.

2022-10-09 21:43 UTC, ArslanDev666 commented on src/components/BurgerIngredients/BurgerType/BurgerType.jsx
> +export const BurgerType = ({ title, list, openModal, id }) => {
**Надо исправить:** Описаны не все propTypes

2022-10-09 21:43 UTC, ArslanDev666 commented on src/components/OrderDetails/OrderDetails.jsx
> +export const OrderDetails = () => {
**Надо испарвить**

для этого компонента так же нужно описать PropTypes

2022-10-09 21:43 UTC, ArslanDev666 commented on src/App.jsx
> +      const data = await getIngredients('ingredients')
**можно лучше:** Немного не логично, что мы используем getIngredients, и еще раз указываем `ingredietns`. В будущем дополнительного апи, для ингредиентов нет, поэтому можно смело, сразу использовать нужный url.

2022-10-10 06:15 UTC, ArtemRav commented on src/App.jsx
> +      const data = await getIngredients('ingredients')
Согласен, глупо вышло. А можете подсказать, почему два раза уходит запрос к API? Запрос ведь только один раз должен срабатывать, при монтировании приложения

2022-10-10 06:15 UTC, ArtemRav commented on src/components/OrderDetails/OrderDetails.jsx
> +export const OrderDetails = () => {
Тут props нет, только orderDetailsCss - убрал декомпозицию, чтобы не сбивала с толку

2022-10-10 12:01 UTC, ArslanMustafin commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +              onClick={() => toggleTab(tab)}
**Можно лучше:** Лучше переделать логику переключения табов по id. Тогда не нужно будет использовать tab.name. tab.name это label вкладки, который служит для отображения информации, id же использовать предпочтительнее, ибо его меняют редко, и он нужен именно для взаимодествия с js.

2022-10-10 12:01 UTC, ArslanDev666 commented on src/App.jsx
> +      const data = await getIngredients('ingredients')
Это связано с работой React.strictMode, подробнее можете загуглить, но если кратко, то он вызывает повторный рендер, чтобы найти ошибки. 
https://reactjs.org/docs/strict-mode.html

2022-10-10 12:02 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

### **Вы молодцы! Работа принята.**

### **Сделает код лучше:**

- В директории `components` Нужно создать папочку `App` и туда поместить компонент `App`.

- Поправить табы, у них изначально должен быть активен 1 таб.

### **_Более подробно эти и более мелкие мелкие замечания, отмечены в коде._**

2022-10-10 18:17 UTC, merged